Feature/update dist
golangci/golangci-lint-action pull request #108
Opened 2020-10-14 04:18 UTC by sayboras

2020-12-29 05:03 UTC, SVilgelm requested changes

2020-12-29 05:03 UTC, SVilgelm commented on .github/workflows/test.yml
> +          git diff --exit-code
one liner should work well
```suggestion
      - run: git diff --exit-code
```

2020-12-29 05:03 UTC, SVilgelm commented on .github/workflows/test.yml
> +            git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
I think it's better to use the `goreleaserbot <goreleaser@carlosbecker.com>`
```suggestion
            git config --local user.name "goreleaserbot"
            git config --local user.email "goreleaser@carlosbecker.com"
```

2020-12-29 05:04 UTC, SVilgelm commented
lets merge it after v2.4.0 released and then we can test it, I don't see any problems here, if it's not working, then we can revert

2021-09-27 09:43 UTC, butuzov commented
@SVilgelm is time to merge (we are currently past due `v2.4.0`)?

2022-02-26 16:22 UTC, SVilgelm commented
finally, let's merge it, more than a year when changes are done :)

2022-02-26 16:23 UTC, SVilgelm approved these changes

2022-02-26 16:26 UTC, merged